import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
  title: "AG-UI Canvas | CopilotKit with LlamaIndex",
  description: "Generated by CopilotKit with LlamaIndex",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="subpixel-antialiased">
        <CopilotKit
          runtimeUrl="/api/copilotkit"
          agent="sample_agent"
          showDevConsole={false}
          publicApiKey={process.env.COPILOT_CLOUD_PUBLIC_API_KEY}
        >
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
